### ISSUE TITLE
Compile error appsettings.json was not found

### ISSUE THREAD

**Issue by charring** [sundryoss/Sundry.PollyDemystified#1]
When building API project

System.IO.FileNotFoundException: 'The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was 'C:\shufflepoint\test\sundryoss\Sundry.PollyDemystified\src\Sundry.PollyDemystified.Api

**Comment by anktsrkr** [comment]
Hi @charring Thanks for raising issue. I intentionally ignored appsettings file. However i see the problem and I fixed it. The solution should be working now, provided you have configured the auth0 correctly.

**Comment by charring** [comment]
Looking at https://auth0.com/blog/securing-aspnet-minimal-webapis-with-auth0

They have in the appconfig.json (following your example)

    "Domain": "xx.eu.auth0.com/"

And in Program.cs  

    c.Authority = $"https://{builder.Configuration["Auth0:Domain"]}";

So FIY you may want to verify your settings.
